---
version: '3.3'
networks:
  game:
    driver: bridge

services:
  api:
    container_name: kalaxia_api
    image: kalaxia/api
    env_file:
      - kalaxia.env
    networks:
      - game
    volumes:
      - "./volumes/rsa_vault:/go/src/kalaxia-game-api/rsa_vault"

  nginx:
    container_name: kalaxia_nginx
    build: nginx
    networks:
        - game
    depends_on:
        - api
    env_file:
        - kalaxia.env
    extra_hosts:
        - "local.kalaxia.com:127.0.0.1"
    volumes:
        - "./volumes/app:/srv/app"
        # nginx
        - "./volumes/ssl:/etc/ssl"
        - "./volumes/html:/usr/share/nginx/html"
        - "./volumes/logs/nginx:/var/log/nginx"
    networks:
        - game
    ports:
        - "${NGINX_HTTPS_PORT}:443"
        - "${NGINX_PORT}:80"

  postgresql:
    container_name: kalaxia_postgresql
    image: postgres:9.6
    env_file:
      - kalaxia.env
    networks:
      - game
    ports:
      - "5432"

  phpgpadmin:
    container_name: kalaxia_phpgpadmin
    image: zhajor/docker-phppgadmin
    env_file:
      - kalaxia.env
    networks:
      - game
    ports:
      - "9090:80"
